### ISSUE TITLE
does not work with pypy

### ISSUE THREAD

**Issue by ghost** [albertz/PyCPython#2]
So PyCPython can't run because of:

> faulthandler import error. No module named faulthandle

It can't be installed on PyPy with pip because of 

> ```
> traceback.c:250:5: note: in expansion of macro ‘PUTS’
>      PUTS(fd, " (most recent call first):\n");
>      ^
> error: command 'cc' failed with exit status 1
> ```

**Comment by albertz** [comment]
Wherever I imported faulthandler, you can just comment out that line, it's not critical for anything.

I think I remember that there were some slight incompatibility with PyPy at some other places and I was too lazy to fix them, although it should not be that complicated. Pull requests are welcome. :)
